apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: dashboard
build:
  platforms: ["linux/amd64"]
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ${IMAGE_REPOSITORY}/dashboard
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
    - name: dashboard
      chartPath: deploy/helm
      valuesFiles:
      - ${VALUES_LOCATION}/dashboard.yaml